"""
Contextually-inferred field name mappings for NCAA Football dynasty tables
that do NOT have matching game CSV exports.

Generated by analyzing exported data patterns, value ranges, cross-table
references, and known college football domain knowledge.

Confidence levels:
  HIGH   = field meaning is clear from data (string content, known cross-table codes,
           or value ranges that uniquely identify the concept)
  MEDIUM = strong inference from patterns/ranges but not 100% certain
  LOW    = educated guess based on field code naming conventions and loose patterns

Source file: OD-Avalanche36OD1_file (NCAA Football 13, 12-user dynasty, Year 3)
"""

FIELD_MAPPINGS = {

    # =========================================================================
    # TEAM (128 records, 195 fields)
    # Main team table - all 128 FBS teams
    # =========================================================================
    "TEAM": {
        # --- Identity / String Fields (HIGH confidence) ---
        "ANDT":  "team_name",                       # HIGH - "Alabama", "USC", etc.
        "ANLT":  "team_location_name",              # HIGH - "Alabama", "UCLA" (often same as ANDT)
        "ANMT":  "team_mascot",                     # HIGH - "Crimson Tide", "Trojans"
        "ANST":  "team_abbreviation",               # HIGH - "Bama", "USC", "Ark St"
        "CCMT":  "team_description",                # HIGH - "Established in 1831", "Rose Bowl Stadium"
        "CNMT":  "team_nickname",                   # HIGH - "Crimson Tide", "Trojans" (often = ANMT)
        "TASC":  "team_ascii_code",                 # HIGH - 6-char code: "ALBAMA", "GEORGA", "MIAMFL", "NOTDAM"
        #   TPGT (next field) equals DIGT and is the schedule team ID

        # --- Primary Keys / IDs (HIGH confidence) ---
        "DIGT":  "team_id",                         # HIGH - unique team ID used in SCHD.GTAG/GTHG (verified 25 teams)
        "DIOT":  "team_original_id",                # HIGH - original/default team ID
        "DIST":  "team_internal_sort_id",           # HIGH - another team ID variant, same range
        "DIGC":  "conference_id",                   # HIGH - maps to CONF.DIGC (0=ACC...11=SEC)
        #   Verified: Alabama DIGC=11 (SEC), Georgia DIGC=11 (SEC)
        "DIGD":  "division_id",                     # HIGH - maps to DIVI.DIGD (0-21, 30=no division)
        "DIGS":  "stadium_id",                      # HIGH - maps to STAD.DIGS
        "DICT":  "city_id",                         # MEDIUM - numeric city/location reference index
        "DIGL":  "league_level",                    # HIGH - 0=FBS, 1=FCS
        "DICN":  "dynasty_change_number",           # LOW - internal change tracking counter

        # --- Uniform/Color Fields (MEDIUM confidence) ---
        # These are appearance index values (0-255), controlling jersey/helmet/pants colors
        "BFFT":  "uniform_base_fill_front",         # MEDIUM - body/jersey fill color index
        "BOFT":  "uniform_base_outline_front",      # MEDIUM - body/jersey outline color index
        "GFFT":  "uniform_glove_fill_front",        # MEDIUM - glove fill color index
        "GOFT":  "uniform_glove_outline_front",     # MEDIUM - glove outline color index
        "DRFT":  "uniform_default_road_fill",       # MEDIUM - road/away jersey color
        "ROFT":  "uniform_road_outline_fill",       # MEDIUM - road jersey outline
        "BCBT":  "uniform_base_color_body",         # MEDIUM - base color for body
        "B2BT":  "uniform_base2_body",              # MEDIUM - secondary base color body
        "G2BT":  "uniform_glove2_body",             # MEDIUM - secondary glove color
        "GCBT":  "uniform_glove_color_body",        # MEDIUM - glove main color
        "R2BT":  "uniform_road2_body",              # MEDIUM - secondary road color
        "RCBT":  "uniform_road_color_body",         # MEDIUM - road color body
        "BDRT":  "team_rating_defense_rush",        # MEDIUM - 25-96 range, team defensive rating
        "BLRT":  "team_rating_defense_line",        # MEDIUM - 9-99 range, defensive line rating
        "BQRT":  "team_rating_defense_qb_pressure", # MEDIUM - 30-99 range
        "BRRT":  "team_rating_defense_run",         # MEDIUM - 30-99 range
        "EDRT":  "team_rating_offense_execution",   # MEDIUM - 34-95 range
        "FORT":  "team_rating_offense_overall",     # MEDIUM - 49-99 range
        "LDRT":  "team_rating_offense_line_drive",  # MEDIUM - 20-96 range
        "LORT":  "team_rating_offense_line_overall", # MEDIUM - 6-96 range
        "RRDT":  "team_roster_depth_ranking",       # MEDIUM - 0-122 range (rank among 128 teams)
        "RROT":  "team_roster_overall_ranking",     # MEDIUM - 0-122 range
        "RRWT":  "team_rating_overall_weighted",    # MEDIUM - 30-99 range
        "VORT":  "team_overall_rating",             # MEDIUM - 36-99 range (overall team quality)
        "BPDT":  "bowl_playoff_dynasty_titles",     # MEDIUM - 0-4 range
        "BPOT":  "bowl_playoff_opponent_target",    # MEDIUM - index 0-130

        # --- Ranking / Prestige (HIGH confidence) ---
        "TSRT":  "team_sort_rating",                # MEDIUM - always 47-99 (but many at 99, so may be cap)
        "TPGT":  "team_page_id",                    # MEDIUM - unique per team 1-232
        "RFTT":  "recruiting_fan_tier",             # HIGH - 0/10/20/.../100 = prestige tier for recruiting
        "NYCN":  "national_championship_count",     # HIGH - Alabama=13, Notre Dame=13, USC=11 (matches history)

        # --- All-Time Historical Records (HIGH confidence) ---
        "WHCT":  "wins_historical_career_total",    # HIGH - Alabama=514, Michigan=589 (all-time wins)
        "LHCT":  "losses_historical_career_total",  # HIGH - Alabama=129 (all-time losses)
        "THCT":  "ties_historical_career_total",    # HIGH - Alabama=24 (all-time ties)
        "SHCT":  "streak_historical_current",       # HIGH - -14 to 11, current win/loss streak
        "IWCT":  "index_win_count_total",           # MEDIUM - historical win count (possibly different era)
        "OLCT":  "overall_loss_count_total",        # MEDIUM - historical loss count

        # --- Bowl Game Historical Records (HIGH confidence) ---
        "WOBC":  "wins_overall_bowl_count",         # HIGH - Alabama=35 bowl wins (matches historical data)
        "LOBC":  "losses_overall_bowl_count",       # HIGH - Alabama=22 bowl losses
        "TOBC":  "titles_overall_bowl_championships",  # MEDIUM - dynasty-era bowl championship wins (0-3)

        # --- Dynasty Season Records (HIGH confidence) ---
        "WSPT":  "wins_season_point_total",         # HIGH - current season wins (Rutgers=14 = undefeated)
        "LSPT":  "losses_season_point_total",       # HIGH - current season losses

        # --- Boolean Status Flags (MEDIUM confidence) ---
        "IWST":  "is_winning_streak",               # MEDIUM - 1 if team is on a winning streak
        "WLST":  "won_last_game",                   # MEDIUM - 1 if won last game (same teams as IWST)
        "WCNT":  "won_conference_championship",     # MEDIUM - 1 for conference champ teams (Pittsburgh, Maryland)
        "LCNT":  "lost_conference_championship",    # MEDIUM - 1 for teams that lost conf championship game
        "WWOG":  "won_week_outright_game",          # MEDIUM - weekly status flag
        "LWOG":  "lost_week_outright_game",         # MEDIUM - weekly status flag
        "LTNT":  "lost_this_season_notable",        # MEDIUM - some season tracking flag
        "WTNT":  "won_this_season_notable",         # MEDIUM - matches IWST pattern
        "LTST":  "lost_title_season",               # MEDIUM - 1 for Alabama, Cal, South Carolina
        "WTST":  "won_title_season",                # MEDIUM - 1 for Miami, Maryland, Texas A&M, SMU
        "OLST":  "overall_loss_season_tracked",     # MEDIUM - season tracking binary
        "OHST":  "on_home_schedule_tracked",        # MEDIUM - most teams = 1
        "EHCT":  "eligible_historical_count_tracked", # MEDIUM - almost all teams = 1
        "CMHT":  "conference_member_historical_tracked", # MEDIUM - most FBS teams
        "SPHT":  "special_postseason_history_tracked", # MEDIUM - subset of teams

        # --- Poll / Award Rankings (HIGH confidence) ---
        "APCT":  "ap_poll_current_rank",            # HIGH - AP poll rank (0=unranked, lower = higher ranked)
        "FPCT":  "coaches_poll_current_rank",       # HIGH - Coaches poll rank (FP = "football poll")
        "APDT":  "ap_poll_delta_rank",              # MEDIUM - change in AP rank
        "FPDT":  "coaches_poll_delta_rank",         # MEDIUM - change in coaches poll rank
        "APST":  "ap_poll_sort_points",             # MEDIUM - AP poll points for ranking
        "FPST":  "coaches_poll_sort_points",        # MEDIUM - coaches poll points

        # --- Voting / Recruiting Prestige (MEDIUM confidence) ---
        # V-prefix fields range 0-11, matching the 12 user teams concept
        # These likely represent recruiting interest factors visible to recruits
        "VASP":  "vote_academic_support_prestige",  # MEDIUM - academic prestige visible to recruits
        "VDTP":  "vote_draft_track_prestige",       # MEDIUM - NFL draft prestige
        "VFAP":  "vote_fan_atmosphere_prestige",    # MEDIUM - fan/atmosphere appeal
        "VFPP":  "vote_fan_passion_prestige",       # MEDIUM - fan passion level
        "VHCP":  "vote_head_coach_prestige",        # MEDIUM - HC reputation
        "VIRT":  "vote_internal_rank",              # MEDIUM - internal ranking index (2-232, non-0-11)
        "VLCP":  "vote_location_campus_prestige",   # MEDIUM - campus/location appeal
        "VNET":  "vote_network_tv_prestige",        # MEDIUM - TV exposure (0-2)
        "VPAP":  "vote_program_atmosphere_prestige", # MEDIUM - program prestige
        "VPCP":  "vote_playing_career_prestige",    # MEDIUM - playing time/career potential
        "VPMT":  "vote_postseason_momentum",        # MEDIUM - 0-41, mostly 0 (recent postseason success)
        "VSPP":  "vote_stadium_proximity_prestige", # MEDIUM - stadium/facilities
        "VVTP":  "vote_visibility_tradition_prestige", # MEDIUM - tradition/visibility

        # --- Internal Reference IDs (MEDIUM confidence) ---
        "IPMT":  "internal_player_min_team",        # MEDIUM - min player ID range for this team
        "OIPT":  "original_internal_player_top",    # MEDIUM - original player range top
        "PACD":  "player_allocation_count_default",  # MEDIUM - player allocation ID
        "PACO":  "player_allocation_count_original", # MEDIUM - original player allocation
        "1IST":  "first_independent_school_tag",    # LOW - 65535 = sentinel for no rivalry opponent
        "2IST":  "second_independent_school_tag",   # LOW - always 65535

        # --- Playbook / Strategy (MEDIUM confidence) ---
        "PCMT":  "playbook_coach_method_type",      # MEDIUM - 0-211, unique per team, playbook assignment
        "SVTT":  "strategy_visual_template_type",   # MEDIUM - 0-252, playbook/strategy visual ID
        "TPCT":  "total_poll_count_track",          # MEDIUM - seems like poll vote totals
        "ppmt":  "poll_points_media_total",         # MEDIUM - similar to TPCT, media poll points

        # --- Color/Visual Hex Data (MEDIUM confidence) ---
        "MNJJ":  "team_color_mask_hex",             # MEDIUM - 26-char hex string, team color bitmask
        "PIPT":  "player_image_palette_type",       # MEDIUM - 14-char hex, uniform palette config
        "OPNI":  "option_panel_index",              # LOW - always 60
        "PDCN":  "palette_default_color_number",    # LOW - always 6

        # --- Team Rankings / Sorting (MEDIUM confidence) ---
        "RPBT":  "rank_points_bowl_total",          # MEDIUM - always 0
        "RPCT":  "rank_points_current_total",       # MEDIUM - 1-255 ranking points
        "RPDT":  "rank_points_defense_total",       # MEDIUM - 0-122 defensive ranking
        "RPOT":  "rank_points_offense_total",       # MEDIUM - 0-122 offensive ranking
        "RVOT":  "rival_opponent_team",             # MEDIUM - team ID of primary rival (0-127)

        # --- Season/Conference Stats (MEDIUM confidence) ---
        "SCPT":  "schedule_conference_position",    # HIGH - 1-13, team's position in conference standings
        "SDPT":  "schedule_division_position",      # HIGH - 1-11, team's position in division
        "WCRC":  "wins_conference_record_count",    # HIGH - 0-12, conference wins
        "LCRC":  "losses_conference_record_count",  # HIGH - 1-42, conference losses (career?)
        "TCRC":  "ties_conference_record_count",    # LOW - always 0

        # --- Dynasty Historical / Career Stats (MEDIUM confidence) ---
        "TPDT":  "total_points_dynasty_total",      # MEDIUM - 0-498, accumulated dynasty points
        "PRCT":  "prestige_rank_current",           # MEDIUM - 0-247, prestige ranking
        "PRGT":  "prestige_rank_game_total",        # MEDIUM - 1-432, related to DROT
        "DROT":  "dynasty_rank_overall_total",      # MEDIUM - 1-432, dynasty-level overall rank
        "LGLT":  "league_level_team",               # MEDIUM - maps near DIGT, sorting index
        "SGLT":  "sort_group_level_team",           # MEDIUM - same as LGLT

        # --- Scheduling / Color Indices (LOW confidence) ---
        "LFMT":  "logo_format",                     # LOW - 0-486, logo/art asset index
        "1ZET":  "zone_endzone_texture_1",          # LOW - 0-486, endzone visual
        "2ZET":  "zone_endzone_texture_2",          # LOW - 0-486, endzone visual
        "1MNS":  "main_number_style_1",             # LOW - always 0
        "AAMT":  "all_time_attendance_max",         # HIGH - Michigan=115144 (matches Big House capacity)
        "RTTA":  "running_total_attendance",         # HIGH - slightly different from AAMT, lifetime attendance
        "MACT":  "mascot_animation_code",           # LOW - 0-511
        "OTTA":  "option_team_type_assignment",     # LOW - mostly 1023 sentinel

        # --- Color Configuration (MEDIUM confidence) ---
        "RYCF":  "render_year_color_fill",          # LOW - 0-263, color palette index
        "RYCN":  "render_year_color_number",        # LOW - 0-263, color palette index
        "SCST":  "schedule_color_scheme_type",      # LOW - -1/0/1
        "SDST":  "schedule_display_style_type",     # LOW - 1-10

        # --- Misc / Recruiting (MEDIUM confidence) ---
        "RAMT":  "recruiting_area_map_tier",        # MEDIUM - 1-6 tier system
        "XRPT":  "extra_recruiting_pipeline_tier",  # MEDIUM - 1-6 tier system
        "SRPT":  "schedule_rivalry_points",         # MEDIUM - 0-68, rivalry importance
        "CMUN":  "championship_unit_number",        # LOW - 0-26
        "REDT":  "record_edit_default_type",        # LOW - always 1
        "RFOT":  "record_format_original_type",     # LOW - always 1
        "ITCT":  "internal_team_conference_tag",    # LOW - 0-58
        "ITST":  "internal_team_sort_tag",          # LOW - always 0
        "NSID":  "network_schedule_id",             # LOW - always 0
        "NYCN":  "national_championship_count",     # (already listed above)
        "PFCT":  "post_final_count_tracked",        # LOW - 0-34
        "PWCT":  "post_week_count_tracked",         # LOW - 0 or 100
        "PWDT":  "post_week_delta_tracked",         # LOW - 0 or 100
        "SIVT":  "season_in_vault_tracked",         # LOW - always 1
        "SQVT":  "season_qualifier_vault_tracked",  # LOW - 0/1 (most = 1)
        "WAUT":  "week_auto_update_tracked",        # LOW - always 1
        "WOST":  "week_original_schedule_tracked",  # LOW - always 0
        "PYTT":  "play_type_team",                  # MEDIUM - 0/1 (FBS/other)

        # --- Lowercase Fields (likely uniform/appearance) ---
        "last":  "logo_alternate_style_toggle",     # LOW - 0/1
        "lbst":  "logo_bowl_style_type",            # LOW - 0 or large index
        "lcst":  "logo_conference_style_type",      # LOW - 0/1
        "ldst":  "logo_division_style_type",        # LOW - 0/1
        "lhst":  "logo_helmet_style_type",          # LOW - 0/1
        "scst":  "schedule_count_season_total",     # MEDIUM - 1-13 (matches conference size)
        "snst":  "season_number_style_type",        # LOW - always 0
        "wast":  "win_alternate_style_toggle",      # LOW - 0/1
        "wbst":  "win_bowl_style_type",             # LOW - 0 or index
        "wcst":  "win_conference_style_type",       # LOW - 0/1
        "wdst":  "win_division_style_type",         # LOW - 0/1
        "whst":  "win_helmet_style_type",           # LOW - 0/1

        # --- Missing/Extra TEAM Fields ---
        "AIMT":  "attendance_index_max_team",       # LOW - 1-110, attendance scaling index
        "LTFT":  "losses_total_format_team",        # LOW - 0-49, season loss tracking
        "LTRT":  "losses_total_road_team",          # LOW - always 0
        "OHUT":  "on_home_user_tracked",            # LOW - always 0
        "OLFT":  "overall_loss_format_team",        # LOW - always 0
        "WTRT":  "wins_total_road_team",            # LOW - always 0

        # --- Always-Zero/Unused Fields ---
        "htAT":  "home_team_auto_toggle",           # LOW - always 0
        "idst":  "internal_data_style_tag",         # LOW - always 0
        "ssAT":  "season_start_auto_toggle",        # LOW - always 0
        "tast":  "team_auto_style_tag",             # LOW - always 0
        "tcst":  "team_color_style_tag",            # LOW - always 0
        "thst":  "team_helmet_style_tag",           # LOW - always 0
        "KRBT":  "kickoff_return_base_template",    # LOW - always 0
        "KRCT":  "kickoff_return_count",            # MEDIUM - 1-128 (unique per team)
        "KRMT":  "kickoff_return_max_template",     # MEDIUM - 1-128 (unique per team)
        "MTPT":  "match_type_point",                # LOW - 0/60, few values
        "DISM":  "division_schedule_map",           # MEDIUM - 0-91, nearly unique
        "PPMT":  "pipeline_point_map_team",         # MEDIUM - 0-123, unique per team (ordering index)
        "CPWT":  "conference_power_weight",         # LOW - 0 or 100
        "CBET":  "conference_bowl_eligibility_threshold", # LOW - always 3
        "ASLT":  "auto_sim_lock_toggle",            # LOW - always 0
        "CBDU":  "conference_bowl_default_unused",  # LOW - always 0
        "OUAT":  "original_user_auto_toggle",       # LOW - always 0
        "ERCT":  "error_count_tracked",             # LOW - always 0
        "TTWT":  "team_template_weight_type",       # LOW - 0/18 only
        "LCNT":  "lost_conference_notable_tracked",  # (already above)

        # --- Conference/Scheduling IDs (MEDIUM) ---
        "TCNS":  "team_conference_neutral_site",    # LOW - always 0
        "TCNT":  "team_conference_number_total",    # LOW - always 0
        "TEFT":  "team_eligible_format_type",       # LOW - always 0
        "TFUT":  "team_future_unused_type",         # LOW - always 0
        "TSPT":  "team_schedule_pointer_total",     # LOW - always 0
        "SUSD":  "suspended_unused_data",           # LOW - always 0
        "RUDS":  "recruit_unused_data_slot",        # LOW - always 0
        "YTTA":  "year_total_team_attendance",      # LOW - 0/264, few values
    },

    # =========================================================================
    # COCH (384 records, 153 fields)
    # Coach table - ~3 coaches per team (HC, OC, DC)
    # =========================================================================
    "COCH": {
        # --- Identity (HIGH confidence) ---
        "DICC":  "coach_id",                        # HIGH - unique coach identifier
        "DIGT":  "team_id",                         # HIGH - team coach belongs to
        "DIOT":  "team_original_id",                # HIGH - original team assignment
        "DINC":  "contract_index",                  # HIGH - index into CONT table
        "ANLC":  "coach_title_label",               # HIGH - "Bama Coach", "AF Coach" etc.
        "MNFC":  "first_name",                      # HIGH - "Anthony", "Steve"
        "MNLC":  "last_name",                       # HIGH - "Bradshaw", "Cannon"
        "SPOC":  "staff_position_on_coaching",      # HIGH - 0=HC, 1=OC, 2=DC
        "DITP":  "destination_team_previous",       # MEDIUM - previous team (1023=never moved)
        "DICN":  "dynasty_change_number",           # LOW - internal change counter
        "DIPC":  "draft_index_player_coach",        # LOW - 0-135
        "DIPP":  "draft_index_position_primary",    # LOW - 0-2 (matches SPOC range)
        "DIDC":  "depth_index_division_coach",      # LOW - 0-4

        # --- Attribute Ratings (HIGH confidence) ---
        "ATDC":  "attribute_defense_coaching",      # HIGH - 35-90 range, def coaching skill
        "ATOC":  "attribute_offense_coaching",      # HIGH - 40-80 range, off coaching skill
        "RTDC":  "rating_defense_coaching",         # HIGH - 40-70 range, defensive rating
        "RTOC":  "rating_offense_coaching",         # HIGH - 18-80 range, offensive rating
        "STDC":  "scouting_defense_coaching",       # HIGH - 40-65 range, scouting ability (def)
        "STOC":  "scouting_offense_coaching",       # HIGH - 40-67 range, scouting ability (off)
        "EGAC":  "experience_games_as_coach",       # MEDIUM - 0-69, career experience level
        "TGHC":  "tenure_games_head_coach",         # MEDIUM - 0-42, games as HC at current team
        "TARC":  "total_attribute_rating_coach",    # MEDIUM - 5-100, overall coach rating
        "CRAC":  "career_rating_accumulated_coach", # MEDIUM - 0-240, accumulated career rating

        # --- Career Win/Loss Records (HIGH confidence) ---
        "NWTC":  "wins_career_total_coach",         # HIGH - career total wins (NWTC+LTOC = total games)
        "LTOC":  "losses_career_total_coach",       # HIGH - career total losses
        "IWCC":  "in_wins_career_count",            # HIGH - matches NWTC (confirmed same values)
        "OLCC":  "overall_losses_career_count",     # HIGH - matches LTOC (confirmed same values)
        "LTTC":  "losses_this_team_count",          # HIGH - losses at current team
        "WTTC":  "wins_this_team_count",            # HIGH - wins at current team
        "LTCP":  "losses_total_career_prior",       # MEDIUM - career losses (may include prior stint)
        "WTCP":  "wins_total_career_prior",         # MEDIUM - career wins at prior teams
        "OLSC":  "overall_losses_season_coach",     # MEDIUM - 0/1, current season loss flag
        "IWSC":  "in_wins_season_coach",            # MEDIUM - 0/1, current season win flag

        # --- Season/Conference Records (HIGH confidence) ---
        "SLCC":  "season_losses_conference_coach",  # HIGH - conference losses this season (2-15)
        "SLSC":  "season_losses_season_coach",      # HIGH - total season losses (same as SLCC often)
        "SWCC":  "season_wins_conference_coach",    # HIGH - conference wins this season
        "SWSC":  "season_win_streak_coach",         # MEDIUM - -12 to 11, current W/L streak
        "TSWC":  "total_season_wins_conference",    # MEDIUM - 0-2, title/conf championship wins
        "NWCC":  "num_wins_career_current",         # MEDIUM - overall career wins (redundant with NWTC)
        "WRCC":  "win_record_career_count",         # MEDIUM - 0-7

        # --- Rivalry Records (MEDIUM confidence) ---
        "LVRC":  "losses_vs_rivals_career",         # MEDIUM - 0-7, rivalry game losses
        "WVRC":  "wins_vs_rivals_career",           # MEDIUM - 0-7, rivalry game wins
        "LROC":  "losses_rivalry_overall_count",    # MEDIUM - 0-7
        "LOCC":  "losses_overall_career_count",     # MEDIUM - 0-21 (another career loss field)
        "L52C":  "losses_last_52_weeks_count",      # MEDIUM - losses in recent year
        "W52C":  "wins_last_52_weeks_count",        # MEDIUM - wins in recent year

        # --- Tendency/Strategy (MEDIUM confidence) ---
        # IB-prefix: seems to be play calling intensity (always 1 or 2)
        "IBCC":  "intensity_blitz_coverage_coach",  # MEDIUM - 1-2, defensive aggressiveness
        "IBFC":  "intensity_blitz_frequency_coach", # MEDIUM - 1-2
        "IBHC":  "intensity_blitz_heavy_coach",     # MEDIUM - 1-2
        "IBLC":  "intensity_blitz_light_coach",     # MEDIUM - 1-2
        "IBQC":  "intensity_blitz_quarterback_coach", # MEDIUM - 1-2
        # TB-prefix: play calling tendencies (0-3 scale = conservative to aggressive)
        "TBFC":  "tendency_formation_coach",        # MEDIUM - 0-3
        "TBHC":  "tendency_hurryup_coach",          # MEDIUM - 2-3
        "TBLC":  "tendency_long_pass_coach",        # MEDIUM - 0-3
        "TBQC":  "tendency_quarterback_coach",      # MEDIUM - 0-3
        "TBRC":  "tendency_run_blocking_coach",     # MEDIUM - 0 or 90 (run tendency pct?)

        # --- Coach Background/Position (MEDIUM confidence) ---
        "POTC":  "position_origin_type_coach",      # MEDIUM - 0-6, which position background
        "PSOC":  "position_specialty_of_coach",     # MEDIUM - 0-6, specialty area
        "ICOC":  "in_conference_opponent_count",    # MEDIUM - 0-30, years in conference?
        "FTLC":  "future_team_lock_coach",          # LOW - always 1023 (sentinel/unused)
        "CLDP":  "coaching_level_depth_position",   # LOW - 0/1

        # --- Recruiting/Prestige (MEDIUM confidence) ---
        "NIOC":  "national_interest_overall_coach", # LOW - always 0
        "KPOC":  "known_prestige_overall_coach",    # LOW - always 0
        "MPOC":  "media_prestige_overall_coach",    # LOW - always 0
        "TFHC":  "tenure_from_hire_count",          # MEDIUM - 1-181, coaching career length in some unit
        "TRNC":  "trend_net_change",                # MEDIUM - -56 to 42, career momentum/trend

        # --- Contract/Salary Related (LOW confidence) ---
        "RAHC":  "rating_after_hire_count",         # LOW - 0-5
        "RYCC":  "remaining_years_contract_coach",  # MEDIUM - 0-2 (matches CONT.RYCC range)
        "RYTC":  "remaining_years_team_coach",      # MEDIUM - 0-2
        "ERPC":  "era_performance_check",           # LOW - 0/6
        "ERFC":  "error_flag_coach",               # LOW - always 0

        # --- Misc Play Style (LOW confidence) ---
        "TCOC":  "team_conference_order_coach",     # LOW - 1-23
        "TGHC":  "tenure_games_head_coach",         # (duplicate - already above)
        "YTOC":  "years_tenure_overall_coach",      # MEDIUM - 0-3
        "ZSBC":  "zero_season_bowl_coach",          # LOW - always 0
        "ghTC":  "games_history_this_career",       # LOW - 0-11
        "50TC":  "fifty_win_tracker_coach",         # LOW - 0-2
        "51TC":  "fifty_one_win_tracker_coach",     # LOW - 0-2
        "52TC":  "fifty_two_win_tracker_coach",     # LOW - 0-2

        # --- Boolean/Flag Fields (LOW confidence) ---
        "AANC":  "award_accolade_national_coach",   # LOW - 0-12
        "AFFC":  "auto_fire_flag_coach",            # LOW - 0/1
        "ARYC":  "at_risk_year_coach",              # LOW - 0/1
        "BBCC":  "bowl_ban_conference_coach",       # LOW - 0-2
        "BLFC":  "buyout_lock_flag_coach",          # LOW - 0/1
        "CPSC":  "coaching_points_season_coach",    # LOW - 0-2
        "CRFC":  "contract_renewal_flag_coach",     # LOW - 0/1
        "CSFC":  "coaching_stability_flag_coach",   # LOW - 0/1
        "CTCC":  "career_titles_conference_coach",  # LOW - 0/3
        "CTNC":  "career_titles_national_coach",    # LOW - 0-2
        "CUFC":  "currently_unemployed_flag_coach", # LOW - 0/1
        "DCYC":  "dynasty_coaching_year_count",     # LOW - 0-2
        "FTCC":  "fired_terminated_career_coach",   # LOW - 0/1
        "GBHC":  "game_bonus_historic_coach",       # LOW - always 0
        "IFSC":  "internal_flag_status_coach",      # LOW - always 1
        "IKSC":  "internal_key_status_coach",       # LOW - 0/1
        "ILOC":  "internal_lock_override_coach",    # LOW - 1-2
        "IRWC":  "internal_reward_coach",           # LOW - always 1
        "ITCC":  "internal_transfer_count_coach",   # LOW - always 0
        "ITDC":  "internal_team_depth_coach",       # LOW - 1-2
        "LCCC":  "loss_count_career_coach",         # LOW - always 0
        "LCCH":  "loss_count_career_history",       # LOW - always 0
        "LFOR":  "locked_for_override",             # LOW - always 0
        "LHFC":  "loss_history_flag_coach",         # LOW - always 0
        "LLBC":  "loss_limit_bowl_coach",           # LOW - 0-2
        "LPWC":  "loss_penalty_week_coach",         # LOW - always 0
        "MEDC":  "media_exposure_default_coach",    # LOW - always 1
        "NLCC":  "national_level_coaching_cap",     # LOW - 0/3
        "NLCP":  "national_level_coaching_points",  # LOW - 0-2
        "NRCC":  "no_recruit_cap_coach",            # LOW - always 0
        "OHWC":  "overall_head_wins_coach",         # LOW - always 0
        "OJCC":  "overall_job_change_coach",        # LOW - always 0
        "PRRC":  "prestige_reputation_rating_coach", # LOW - 0/1
        "PTCC":  "promotion_track_career_coach",    # LOW - always 0
        "PXSC":  "prestige_xp_season_coach",        # LOW - 0 or 478
        "RFFC":  "recruit_focus_flag_coach",        # LOW - 0/1
        "RRFC":  "recruit_rating_flag_coach",       # LOW - 0/1
        "S1RC":  "season_1_record_coach",           # LOW - always 0
        "S2RC":  "season_2_record_coach",           # LOW - always 0
        "S3RC":  "season_3_record_coach",           # LOW - always 0
        "S4RC":  "season_4_record_coach",           # LOW - always 0
        "S5RC":  "season_5_record_coach",           # LOW - always 0
        "SASC":  "season_active_status_coach",      # LOW - always 1
        "SHNT":  "season_hire_number_tracking",     # LOW - 0-2
        "SPLC":  "special_locked_coach",            # LOW - always 0
        "SQEC":  "season_qualifier_eligible_coach", # LOW - always 0
        "SWRC":  "season_win_record_coach",         # MEDIUM - -12 to 10, another streak/delta
        "SXEC":  "season_xp_earned_coach",          # LOW - 0-2
        "TEDC":  "tenure_experience_depth_coach",   # LOW - 0-3
        "TFSC":  "tenure_flag_status_coach",        # LOW - 0/3
        "THOC":  "tenure_history_overall_coach",    # LOW - 0-2
        "TLOC":  "tenure_level_overall_coach",      # LOW - 0-3
        "TNCC":  "tenure_national_championship_coach", # LOW - always 0
        "TRWC":  "tenure_rivalry_wins_coach",       # LOW - 0-3
        "TSDC":  "tenure_season_division_coach",    # LOW - 0-3
        "TSOC":  "tenure_seasons_overall_coach",    # LOW - 0-4
        "TTCC":  "tenure_total_career_coach",       # LOW - 0-2
        "TTDC":  "tenure_total_division_coach",     # LOW - 0-3
        "TTLC":  "tenure_total_level_coach",        # LOW - always 0
        "TTWC":  "tenure_total_wins_coach",         # LOW - always 0
        "VPHP":  "vote_prestige_head_position",     # MEDIUM - 0-11, recruiting prestige rating
        "WANC":  "wins_accolade_national_coach",    # LOW - 0-7
        "WCCC":  "win_count_career_coach",          # LOW - always 0
        "WCCH":  "win_count_career_history",        # LOW - always 0
        "WLBC":  "win_limit_bowl_coach",            # LOW - 0-2
        "WSCC":  "win_season_conference_coach",     # LOW - 0-2
        "WTCC":  "win_total_career_coach",          # LOW - 0-2
        "WTHC":  "win_this_half_coach",             # LOW - 0/1
        "WTNC":  "win_this_national_coach",         # LOW - 0/1
        "XBCC":  "xp_bonus_career_coach",           # LOW - 0/3
        "XECC":  "xp_earned_career_coach",          # LOW - always 0
        "YFCC":  "years_fired_career_coach",        # LOW - 0-5
        "YTDC":  "years_tenure_depth_coach",        # LOW - 0 or 95
        "YTHC":  "years_tenure_history_coach",      # LOW - 0-2
        "wgTC":  "win_games_this_career",           # LOW - 0/1
    },

    # =========================================================================
    # BOWL (45 records, 17 fields)
    # Bowl game definitions
    # =========================================================================
    "BOWL": {
        "EMNB":  "bowl_name",                       # HIGH - "GoDaddy.com Bowl", "Rose Bowl", etc.
        "DFMB":  "date_field_map_bowl",             # HIGH - day of year (147-242 = late May to late Aug calendar)
        "DOTG":  "day_of_time_game",                # HIGH - time of day in minutes? (660-1230)
        "DIGS":  "stadium_id",                      # HIGH - maps to STAD.DIGS
        "MNGS":  "matchup_number_game_sequence",    # HIGH - schedule week index (-1 to 40)
        "NWES":  "number_week_end_season",          # HIGH - week number (16-21)
        "NOMB":  "number_of_month_bowl",            # MEDIUM - 1 or 12 (January or December)
        "1ICB":  "conference_1_index_bowl",          # HIGH - conf ID for team 1 tie-in (maps to CONF.DIGC)
        "1RCB":  "conference_1_rank_bowl",           # MEDIUM - rank position from conf 1 (1-8)
        "2ICB":  "conference_2_index_bowl",          # HIGH - conf ID for team 2 tie-in
        "2RCB":  "conference_2_rank_bowl",           # MEDIUM - rank position from conf 2 (1-8)
        "XDIB":  "external_display_index_bowl",     # MEDIUM - 0-44, unique bowl sort order
        "DITU":  "display_template_unique",         # MEDIUM - 1-120, visual template ID
        "OLPB":  "order_list_position_bowl",        # MEDIUM - 0-39, display ordering
        "YADB":  "year_added_bowl",                 # MEDIUM - 1-31, bowl history/age indicator
        "EPWS":  "enabled_postseason_week_schedule", # MEDIUM - 0/1, is bowl active in schedule
        "OGLB":  "order_group_level_bowl",          # MEDIUM - 0-62, internal sort index
    },

    # =========================================================================
    # CONF (25 records, 5 fields)
    # Conference definitions
    # =========================================================================
    "CONF": {
        "MANC":  "conference_name",                 # HIGH - "ACC", "Big Ten", "SEC", etc.
        "DIGC":  "conference_id",                   # HIGH - unique conference index (0-24)
        "DIGL":  "league_level",                    # HIGH - 0=FBS, 1=FCS, 2=Historic, 3=Fantasy, 4=HS
        "RPNC":  "represented_in_polls_national",   # MEDIUM - 0/1, whether conf teams appear in rankings
        "lcCN":  "lower_case_conference_number",    # LOW - always 0
    },

    # =========================================================================
    # DIVI (22 records, 4 fields)
    # Division definitions within conferences
    # =========================================================================
    "DIVI": {
        "MAND":  "division_full_name",              # HIGH - "Pac-12 (North)", "SEC (East)"
        "MNDS":  "division_short_name",             # HIGH - "North", "East", "Leaders"
        "DIGC":  "conference_id",                   # HIGH - parent conference (maps to CONF.DIGC)
        "DIGD":  "division_id",                     # HIGH - unique division index (0-21)
    },

    # =========================================================================
    # STAD (185 records, 117 fields)
    # Stadium definitions
    # =========================================================================
    "STAD": {
        # --- Identity (HIGH confidence) ---
        "MANS":  "stadium_name",                    # HIGH - "Bryant-Denny Stadium", "Rose Bowl"
        "NNTS":  "stadium_nickname",                # HIGH - "The Big House", "Happy Valley", ""
        "ANDT":  "stadium_location_team",           # HIGH - team/city name ("Alabama", "Penn State")
        "TICS":  "team_in_city_stadium",            # HIGH - city name ("Tuscaloosa", "University Park")
        "AATS":  "ascii_abbreviation_team_stadium", # HIGH - 6-char code matching TEAM.TASC
        "DILF":  "display_id_logo_format",          # HIGH - 6-char code (same as AATS)
        "ANMT":  "animation_mascot_type",           # LOW - always "GATORS" (placeholder/default)
        "DIGS":  "stadium_id",                      # HIGH - unique stadium identifier
        "DIUS":  "display_id_unique_stadium",       # HIGH - alternate stadium ID
        "DROS":  "display_row_order_stadium",       # MEDIUM - 0-183, sort ordering

        # --- Capacity (HIGH confidence) ---
        "PACS":  "primary_attendance_capacity_stadium", # HIGH - Michigan Stadium=109901 (matches real capacity)
        "EUCS":  "endzone_upper_capacity_section",  # MEDIUM - always 10000 (expansion section)
        "LLCS":  "lower_level_capacity_section",    # MEDIUM - always 15000
        "LMCS":  "lower_mid_capacity_section",      # MEDIUM - always 15000
        "LUCS":  "lower_upper_capacity_section",    # MEDIUM - always 30000

        # --- Geographic Coordinates (HIGH confidence) ---
        "NOLS":  "north_longitude_stadium",         # HIGH - 71-158 range (longitude degrees, inverted sign)
        "TALS":  "team_area_latitude_stadium",      # HIGH - 21-48 range (latitude degrees, matches US geography)
        "TRTS":  "terrain_rotation_stadium",        # MEDIUM - 0-337.5, field orientation angle

        # --- Visual/Rendering (MEDIUM confidence) ---
        "SERS":  "serial_number_stadium",           # MEDIUM - 0-257, unique visual asset ID
        "CLCW":  "climate_code_weather",            # MEDIUM - 0-51, weather/climate zone
        "TATS":  "team_area_terrain_state",         # MEDIUM - 0-51, state terrain code
        "RDTS":  "reference_data_team_stadium",     # MEDIUM - 1-127, team reference
        "SHTS":  "shared_team_stadium",             # MEDIUM - 0/1, is stadium shared
        "FOTS":  "field_orientation_type_stadium",  # MEDIUM - -5 to 0
        "1STS":  "first_secondary_team_stadium",    # MEDIUM - -1/0 (secondary tenant team)
        "2STS":  "second_secondary_team_stadium",   # LOW - always -1

        # --- Stadium Surface/Config (LOW confidence) ---
        "DYCS":  "dynasty_config_stadium",          # LOW - 0-317
        "ERCS":  "error_config_stadium",            # LOW - always 0
        "ACTS":  "active_config_toggle_stadium",    # LOW - 0/1
        "IROS":  "indoor_roof_open_stadium",        # MEDIUM - 0/1 (dome/retractable roof)
        "NFTS":  "night_field_type_stadium",        # LOW - 0-11
        "NGTS":  "night_game_type_stadium",         # LOW - 0-3
        "TPGS":  "turf_playing_grass_stadium",      # MEDIUM - 0-3 (turf type)
        "RPTS":  "retractable_partial_type_stadium", # LOW - 0/1
        "TOIS":  "type_outdoor_indoor_stadium",     # MEDIUM - 0/1 (0=outdoor, 1=indoor)
        "TSBS":  "type_structure_build_stadium",    # LOW - 0/2

        # --- Visual Effects (LOW confidence) ---
        "XLMS":  "x_length_model_stadium",          # MEDIUM - 0-472, visual model x-axis
        "YLMS":  "y_length_model_stadium",          # MEDIUM - 0-282, visual model y-axis
        "YRTS":  "year_renovation_type_stadium",    # LOW - 0-3
        "YTFS":  "year_turf_format_stadium",        # LOW - 0-6
        "ORYS":  "original_year_stadium",           # LOW - always 81

        # --- Track/Surface Detail (LOW confidence) ---
        # Color-coded track/surface values
        "cfTS":  "color_fill_track_stadium",        # LOW - always 0
        "clTS":  "color_line_track_stadium",        # LOW - always 0
        "cltS":  "color_left_track_stadium",        # LOW - 0-65281
        "frTS":  "fence_right_track_stadium",       # LOW - 0-65281
        "irTS":  "inner_ring_track_stadium",        # LOW - 0-64001
        "lcTS":  "left_corner_track_stadium",       # LOW - 0-64193
        "llTS":  "lower_left_track_stadium",        # LOW - always 0
        "lrTS":  "lower_right_track_stadium",       # LOW - always 0
        "rRTS":  "right_ring_track_stadium",        # LOW - 0-64193
        "rcts":  "right_corner_track_stadium",      # LOW - always 0
        "rlTS":  "right_level_track_stadium",       # LOW - 0-60367
        "rrTS":  "right_row_track_stadium",         # LOW - always 0
        "pwTS":  "power_weather_track_stadium",     # LOW - 0-29
        "stTS":  "style_type_track_stadium",        # LOW - 0-99
        "tjTS":  "type_jumbotron_track_stadium",    # LOW - 0-80
        "wfTS":  "weather_factor_track_stadium",    # LOW - 0-29

        # --- PS-prefix: Stadium Section Visual Presets (all zeros in this save) ---
        # 00PS through 91PS: all 0, likely per-section visual override slots
        "ATZE":  "away_team_zone_endzone",          # LOW - always empty string
        "BTZE":  "base_team_zone_endzone",          # LOW - always empty string
        "CTZE":  "custom_text_zone_endzone",        # LOW - always 0
        "GBZE":  "game_banner_zone_endzone",        # LOW - always 0
        "TTZE":  "team_text_zone_endzone",          # LOW - always 0

        # --- Scoreboard/Display (LOW confidence) ---
        "PFWS":  "priority_front_wall_score",       # LOW - 0/85
        "PRWS":  "priority_rear_wall_score",        # LOW - 0/25
        "PSWS":  "priority_side_wall_score",        # LOW - 0/30
        "PWWS":  "priority_wide_wall_score",        # LOW - 0-33
        "SCCS":  "scoreboard_config_code_stadium",  # LOW - always 10867
        "SFMS":  "scoreboard_format_model_stadium", # LOW - always 0
        "TARS":  "text_alignment_reference_stadium", # LOW - always 99
        "BLCS":  "baseline_config_stadium",         # LOW - always 133

        # --- PS-prefix: Stadium Section Visual Presets (all zeros) ---
        # These 26 fields represent per-section visual overrides, all zeroed out in this save
        "00PS":  "section_preset_0_0", "01PS":  "section_preset_0_1", "02PS":  "section_preset_0_2",
        "10PS":  "section_preset_1_0", "11PS":  "section_preset_1_1", "12PS":  "section_preset_1_2",
        "20PS":  "section_preset_2_0", "21PS":  "section_preset_2_1", "22PS":  "section_preset_2_2",
        "30PS":  "section_preset_3_0", "31PS":  "section_preset_3_1", "32PS":  "section_preset_3_2",
        "40PS":  "section_preset_4_0", "41PS":  "section_preset_4_1", "42PS":  "section_preset_4_2",
        "50PS":  "section_preset_5_0", "51PS":  "section_preset_5_1", "52PS":  "section_preset_5_2",
        "60PS":  "section_preset_6_0", "61PS":  "section_preset_6_1",
        "70PS":  "section_preset_7_0", "71PS":  "section_preset_7_1",
        "80PS":  "section_preset_8_0", "81PS":  "section_preset_8_1",
        "90PS":  "section_preset_9_0", "91PS":  "section_preset_9_1",

        # --- Remaining Always-Zero/Low-Value Fields ---
        "AFTS":  "active_field_type_stadium",       # LOW - always 0
        "BBFS":  "banner_border_fill_stadium",      # LOW - always 0
        "BGUS":  "background_usage_stadium",        # LOW - always 0
        "EWFS":  "endwall_format_stadium",          # LOW - always 0
        "HTPM":  "halftime_performance_model",      # LOW - always 0
        "ITFS":  "internal_turf_format_stadium",    # LOW - always 0
        "MBFS":  "main_banner_fill_stadium",        # LOW - always 0
        "PSFS":  "private_suite_format_stadium",    # LOW - always 0
        "PYTS":  "pylon_type_stadium",              # LOW - always 0
        "SBFS":  "side_banner_fill_stadium",        # LOW - always 0
        "TFFS":  "ticket_format_fill_stadium",      # LOW - always 0
        "TNGS":  "tunnel_gate_stadium",             # LOW - always 0
        "TRGS":  "track_guard_stadium",             # LOW - always 1
        "TUFS":  "tunnel_format_stadium",           # LOW - always 0
        "YTKS":  "year_ticket_kiosk_stadium",       # LOW - always 0
        "bbFS":  "billboard_fill_stadium",          # LOW - always 0
        "fTUS":  "field_turf_usage_stadium",        # LOW - 0/1
        "ggTS":  "gate_ground_type_stadium",        # LOW - always 0
        "tfSS":  "turf_format_side_stadium",        # LOW - always 0
        "txTS":  "text_type_stadium",               # LOW - always 0
        "vtTS":  "visual_theme_type_stadium",       # LOW - 0-8
    },

    # =========================================================================
    # CITY (224 records, 21 fields)
    # Cities/locations used for recruiting
    # =========================================================================
    "CITY": {
        "MNYC":  "city_name",                       # HIGH - "Miami", "Ann Arbor", etc.
        "PNYC":  "promo_news_year_city",            # HIGH - URL/promo text string for local news
        "POPC":  "population_count",                # HIGH - 2896016 for Miami (metro area population)
        "TSYC":  "territory_state_year_city",       # HIGH - "Florida", "Michigan", etc. (state name)
        "WFYC":  "weather_factor_year_city",        # HIGH - 0-34, climate/temperature index
        "DHCR":  "data_hash_code_recruit",          # MEDIUM - unique city identifier hash
        "DIYC":  "display_index_year_city",         # HIGH - 0-412, unique city index
        "DMTC":  "distance_metro_travel_city",      # MEDIUM - 0-99, possibly a distance/desirability metric
        "GERC":  "geographic_region_code",          # MEDIUM - 0-5, recruiting region (6 regions)
        "ISYC":  "index_state_year_city",           # MEDIUM - 0-51, state index (52 states incl DC/Canada)
        "JAYC":  "january_year_city",               # MEDIUM - 0-80, winter temperature/climate metric
        "MOYC":  "metro_or_year_city",              # MEDIUM - 0/1, metro area flag
        "NGER":  "number_geographic_region",        # LOW - always 0
        "PFYC":  "pipeline_factor_year_city",       # LOW - always 70
        "PRYC":  "precipitation_rain_year_city",    # MEDIUM - 0-25, rainfall/precipitation index
        "PSYC":  "population_secondary_year_city",  # LOW - 0-50, secondary population metric
        "PWYC":  "precipitation_winter_year_city",  # MEDIUM - 0-34, winter precip/snow index
        "SAYC":  "summer_average_year_city",        # MEDIUM - 50-99, summer temperature index
        "VTYC":  "vegetation_terrain_year_city",    # LOW - 0-8, terrain/vegetation type
        "WWYC":  "winter_weather_year_city",        # MEDIUM - 0-35, winter temperature index (matches WFYC)
        "ZITC":  "zone_index_terrain_city",         # LOW - 0-3, terrain zone category
    },

    # =========================================================================
    # HEIS (10 records, 11 fields)
    # Heisman Trophy candidates - top 10
    # =========================================================================
    "HEIS": {
        "DIGP":  "player_id",                       # HIGH - maps to PLAY.DIGP
        "PACP":  "points_accumulated_candidate_player", # HIGH - Heisman voting points (180,160,140...)
        "0NAC":  "zero_national_award_count",       # LOW - always 0
        "CcAP":  "conference_coach_award_points",   # MEDIUM - conference-level coach voting points
        "CsAP":  "conference_stat_award_points",    # MEDIUM - conference-level stat points
        "KRPH":  "known_rank_position_heisman",     # HIGH - 0-15, candidate ranking position
        "ScAP":  "statistical_coach_award_points",  # MEDIUM - stats-based coach voting
        "SsAP":  "statistical_stat_award_points",   # MEDIUM - stats-based statistical points
        "VcAP":  "vote_coach_award_points",         # MEDIUM - direct coach voting
        "VsAP":  "vote_stat_award_points",          # MEDIUM - direct statistical voting
        "ytAP":  "year_type_award_points",          # MEDIUM - 3/5/14, category type identifier
    },

    # =========================================================================
    # CONT (369 records, 12 fields)
    # Coach contracts
    # =========================================================================
    "CONT": {
        "DICC":  "coach_id",                        # HIGH - maps to COCH.DICC
        "DIGT":  "team_id",                         # HIGH - maps to TEAM.DIGT
        "DINC":  "contract_index",                  # HIGH - unique contract index (1-611)
        "SPOC":  "staff_position_on_coaching",      # HIGH - 0=HC, 1=OC, 2=DC (matches COCH.SPOC)
        "RYCC":  "remaining_years_contract_coach",  # HIGH - 1-4 years remaining on contract
        "NMRT":  "negotiated_money_rate_total",     # HIGH - -84 to -7, salary amount (negative = payout)
        "XMRT":  "max_money_rate_total",            # HIGH - 10-64, max salary/buyout amount
        "ULAV":  "universal_level_attribute_value",  # MEDIUM - 8-16, coach value/prestige level
        "ICOR":  "index_coach_origin_reference",    # MEDIUM - 0 or 65535 (65535=original, other=hired from)
        "DNIS":  "dynasty_number_index_serial",     # LOW - always 1
        "EICC":  "expiration_index_contract_coach", # LOW - always 0
        "XEIC":  "extra_expiration_index_contract", # LOW - always 0
    },

    # =========================================================================
    # INJY (8 records, 7 fields)
    # Active injuries
    # =========================================================================
    "INJY": {
        "DIGP":  "player_id",                       # HIGH - maps to PLAY.DIGP
        "DIGT":  "team_id",                         # HIGH - maps to TEAM.DIGT
        "LJNI":  "length_injury",                   # HIGH - 32-254, injury duration (higher = longer)
        "TJNI":  "type_injury",                     # HIGH - injury type code (126-196 range)
        "NWES":  "number_week_end_season",          # HIGH - always 0 (active injury in current week)
        "RINI":  "recovery_index_injury",           # LOW - always 0
        "RJNI":  "rehab_job_number_injury",         # LOW - always 1
    },

    # =========================================================================
    # SEAI (1 record, 20 fields)
    # Current season/dynasty state
    # =========================================================================
    "SEAI": {
        "RYES":  "run_year_end_season",             # HIGH - 2 = year 3 (0-indexed dynasty year)
        "NWES":  "number_week_end_season",          # HIGH - 1 = current week
        "TWES":  "type_week_end_season",            # HIGH - 1 = regular season type
        "WOES":  "week_of_end_season",              # HIGH - 22 = total weeks in season
        "BRES":  "bowl_round_end_season",           # MEDIUM - 3 = bowl round/phase indicator
        "PFES":  "pre_final_end_season",            # MEDIUM - 15 = regular season end week
        "WPNS":  "week_postseason_number_start",    # MEDIUM - 7 = postseason start reference
        "WRES":  "week_regular_end_season",         # MEDIUM - 15 = last regular season week
        "EYSS":  "ending_year_season_start",        # MEDIUM - 2 = same as RYES
        "ISES":  "is_season_end_state",             # MEDIUM - 0 = season not ended
        "PCNS":  "postseason_championship_number_state", # LOW - 0
        "PDNS":  "postseason_division_number_state", # LOW - 0
        "PWNS":  "postseason_week_number_state",    # LOW - 0
        "WOGS":  "week_original_game_state",        # LOW - 0
        "WSES":  "week_season_end_state",           # LOW - 0
        "BPNS":  "bowl_postseason_number_state",    # LOW - 0
        "GTSS":  "game_type_season_state",          # MEDIUM - 1 (regular season game type)
        "TSES":  "total_seasons_end_state",         # LOW - 0
        "WRBS":  "week_regular_bowl_state",         # LOW - 0
        "WRFS":  "week_regular_final_state",        # LOW - 0
    },

    # =========================================================================
    # SCHD (788 records, 20 fields) - VERIFIED via cross-reference
    # Schedule table - all regular season + bowl/postseason games
    #
    # Verified by matching TDB SCHD dump (/tmp/dynasty_schd.csv, 788 records)
    # against game-exported CSV (Schedule_Avalanche36OD1.csv, 747 records).
    #
    # Method: Matched 10 played games by unique score pairs, then validated
    # team IDs against TEAM table DICT+1-indexed codes, and validated week
    # numbers across 7 different weeks using known team schedules.
    #
    # Record count difference: TDB has 788 rows (includes ~40 bowl/postseason
    # placeholder slots with GTAG=GTHG=1023 and ISES=0). Game CSV has 747
    # rows (regular season only, Weeks 1-15).
    # =========================================================================
    "SCHD": {
        # --- Game Time (HIGH confidence) ---
        "DOTG": "day_of_time_game",
        # Game start time in minutes from midnight.
        # 720=12:00PM, 750=12:30PM, 780=1:00PM, 930=3:30PM,
        # 1080=6:00PM, 1170=7:30PM, 1200=8:00PM, 1260=9:00PM

        # --- Season Type (HIGH confidence) ---
        "ISES": "is_season_type",
        # 2 = regular season, 0 = bowl/postseason/special game

        # --- Scores (HIGH confidence, 10/10 verified) ---
        "CSAG": "combined_score_away_game",     # -> GameCSV.AwayScore (direct)
        "CSHG": "combined_score_home_game",     # -> GameCSV.HomeScore (direct)

        # --- Game Sequence (MEDIUM confidence) ---
        "MNGS": "matchup_number_game_sequence",
        # Internal ordering index (0-72 regular season)

        # --- Day of Week (HIGH confidence) ---
        "TADG": "time_and_day_game",
        # Day of week: 5=Saturday, 4=Friday, 0-3,6=other (bowl games)

        # --- Week Number (HIGH confidence, 7 distinct weeks verified) ---
        "TWES": "the_week_end_season",          # -> GameCSV.WeekNum via TWES+1

        # --- Game Status (HIGH confidence) ---
        "ATSG": "after_the_score_game",
        # 1=scheduled/unplayed, 2=played-away-won, 3=played-home-won

        # --- Home Team Index (HIGH confidence) ---
        "DIGS": "display_index_game_schedule",
        # Always equals GTHG - 1 (0-indexed home team ID)

        # --- Neutral/Special Site Flag (MEDIUM confidence) ---
        "ETUG": "extra_team_usage_game",
        # 0=normal, 1=special/neutral-site game

        # --- Team IDs (HIGH confidence, 10/10 verified) ---
        "GTAG": "game_team_away_game",          # -> GameCSV.AwayTeam (via team_id_lookup)
        "GTHG": "game_team_home_game",          # -> GameCSV.HomeTeam (via team_id_lookup)
        # Values match TEAM.DIGT (also = TEAM.TPGT); 1023=TBD (bowl placeholder)

        # --- Kickoff/Conference Flags (MEDIUM confidence) ---
        "KCPC": "kickoff_conference_pick_choice",
        # -1=most unplayed, 0 or 1 for played/rivalry games
        "KCPH": "kickoff_conference_pick_home",
        # Paired with KCPC, same pattern

        # --- Alternate Week Number (MEDIUM confidence) ---
        "NWES": "number_week_end_season",
        # Equals TWES for regular season; diverges for postseason

        # --- Dynasty Year (HIGH confidence) ---
        "RYES": "run_year_end_season",
        # 0=previous context, 2=current dynasty year (matches SEAI.RYES)

        # --- Overtime Flag (LOW confidence) ---
        "TOFG": "the_overtime_flag_game",
        # Always 0 in observed data; may flag overtime games

        # --- User Team Flags (MEDIUM confidence) ---
        "UFFG": "user_flag_first_game",         # 0 or 1 for user-tracked games
        "UHFG": "user_flag_home_game",          # 0 or 1, paired with UFFG

        # --- Format/Mode Flag (MEDIUM confidence) ---
        "XFMG": "extra_format_mode_game",
        # 1=regular season (ISES=2), 0=bowl/special (ISES=0)
    },
}


# =============================================================================
# SCHD -> GameCSV cross-reference verification results
# =============================================================================

# Verified team ID samples (TEAM.DIGT value -> team name):
# Used to confirm SCHD.GTAG/GTHG mappings in 10 played games.
# Also matches TEAM.TPGT (field at position 68, right after TASC 6-char code).
SCHD_TEAM_ID_SAMPLES = {
    1:   "Air Force",
    3:   "Alabama",
    5:   "Arizona State",
    6:   "Arkansas",
    13:  "Boston College",
    17:  "Cal",
    18:  "UCF",
    30:  "Georgia",
    35:  "Illinois",
    41:  "Kent State",
    42:  "Kentucky",
    45:  "LSU",
    47:  "Maryland",
    49:  "Miami",
    55:  "Mississippi State",
    67:  "Northwestern",
    68:  "Notre Dame",
    77:  "Pittsburgh",
    80:  "Rutgers",
    83:  "SMU",
    84:  "South Carolina",
    88:  "Syracuse",
    91:  "Tennessee",
    93:  "Texas A&M",
    106: "Vanderbilt",
}

# Complete verified field-to-GameCSV column mappings with verification counts.
# Only fields with direct GameCSV equivalents are included.
SCHD_TO_GAME_CSV_MAPPINGS = {
    # TDB_Field: (GameCSV_Column, Transformation, Verified_Count, Notes)
    "CSHG": ("HomeScore",  "direct",         10, "10/10 played games matched exactly"),
    "CSAG": ("AwayScore",  "direct",         10, "10/10 played games matched exactly"),
    "GTHG": ("HomeTeam",   "team_id_lookup", 10, "10/10 via TEAM.DIGT (=TEAM.TPGT)"),
    "GTAG": ("AwayTeam",   "team_id_lookup", 10, "10/10 via TEAM.DIGT (=TEAM.TPGT)"),
    "TWES": ("WeekNum",    "add_1",           7, "7 distinct weeks verified: TWES+1=WeekNum"),
    # GameCSV columns with NO TDB SCHD equivalent:
    # Q1Home, Q1Away, Q2Home, Q2Away, Q3Home, Q3Away, Q4Home, Q4Away, OTHome, OTAway
    # (Quarter scores are NOT stored in the TDB SCHD table)
}

# The 10 verified game matches used for cross-referencing:
SCHD_VERIFICATION_GAMES = [
    # (TDB_line, CSHG, CSAG, GTHG, GTAG, CSV_HomeTeam, CSV_AwayTeam, CSV_Week)
    (48,   3, 42, 106,  91, "Vanderbilt",       "Tennessee",     1),
    (84,  31, 34,   6,  67, "Arkansas",          "Northwestern",  1),
    (222, 17, 31,  42,   1, "Kentucky",          "Air Force",     1),
    (241, 35, 25,  55,  41, "Mississippi State",  "Kent State",    1),
    (323, 21,  7,  49,  30, "Miami",             "Georgia",       1),
    (327, 44, 38,  45,  84, "LSU",               "South Carolina",1),
    (340, 38, 17,  93,   3, "Texas A&M",         "Alabama",       1),
    (476,  3, 36,  68,  83, "Notre Dame",        "SMU",           1),
    (541, 28, 34,  17,  47, "Cal",               "Maryland",      1),
    (648, 28, 49,  35,  77, "Illinois",          "Pittsburgh",    1),
]


# Print summary
if __name__ == "__main__":
    total_fields = 0
    for table, fields in FIELD_MAPPINGS.items():
        print(f"{table}: {len(fields)} fields mapped")
        total_fields += len(fields)
    print(f"\nTotal fields mapped: {total_fields}")
    print(f"\nSCHD -> GameCSV verified mappings: {len(SCHD_TO_GAME_CSV_MAPPINGS)} fields")
    print(f"Verification games used: {len(SCHD_VERIFICATION_GAMES)}")
    print(f"Team IDs verified: {len(SCHD_TEAM_ID_SAMPLES)}")
